### ISSUE TITLE
docs.battlesnake.io navigation hidden at window widths below 992px

### ISSUE THREAD

**Issue by weslord** [battlesnakeio/roadmap#236]

**Comment by brandonb927** [comment]
@weslord thanks for reporting this! We'll get it fixed and rolled out today. I'll update here when that's been done too.

**Comment by brandonb927** [comment]
Hey I totally forgot to notify that this was fixed! Thanks for the report @weslord

**Comment by weslord** [comment]
@brandonb927 I've hard refreshed and tried a few different browsers and I still can't navigate the docs on small screen sizes.

**Comment by brandonb927** [comment]
Oof you're right. We fixed something else related to this and I assumed this was too. @codeallthethingz is there anything we can do here?
